### PR TITLE
adds daily swarm 0000002

### PR DESCRIPTION
**Pull request by xh3b4sd**
Second day, second post. Lets roll. I think there should be no issues here with the tone.

### CODE REVIEW

**Comment by xh3b4sd** [comment]
Cool, thank you. When it looks good to you then feel free to also approve. When there are more approvals required I can wait for reviewers regardless.

**Comment by tommyhobin** [comment]
So my question is, what does the merge do now, where does it go? Best practice from here is, I'll be scheduling directly through Hubspot for tracking and monitoring to go out immediately. We good with that?

**Comment by tommyhobin** [comment]
Oh, and to make sure we don't rush these out, I think it would make sense to script one today for tomorrow so it can go out in the early a.m. compared to later.

**Comment by xh3b4sd** [comment]
> So my question is, what does the merge do now, where does it go? Best practice from here is, I'll be scheduling directly through Hubspot for tracking and monitoring to go out immediately. We good with that?

Right now the merge doesn't do anything. When you just want to setup the pipeline and make the merge publish or queue the post, fine with me. 

> Oh, and to make sure we don't rush these out, I think it would make sense to script one today for tomorrow so it can go out in the early a.m. compared to later.

+1, I will just push one per day and see how it goes. As we experienced there might be posts which are controversial and take longer to review/merge.

**Comment by tommyhobin** [comment]
Great, thanks for the quick feedback. I am going to schedule for tomorrow morning. And we'll get this process in place.

**Comment by xh3b4sd** [comment]
Can you wrap up how the process or the pipeline then looks like? Just a couple of bullet points so I get the big picture. Also, can I just merge this now when I got a couple of approvals and be comfortable with it or do you need the merge event later on once the publishing pipeline is set up?

**Comment by xh3b4sd** [comment]
IMO people who do not something should ask a question. Then we get the conversation started. Question is if and how we are able to perceive these engagements so we can react and point the right individuals to it to respond.

**Comment by rossf7** [comment]
Good point about the conversation. Mentions will go to whoever gets those for @giantswarm. You could include your user in the tweet. Not sure how else to solve that.

**Comment by xh3b4sd** [comment]
Can we maybe setup something in the Slack blog noise channel?

**Comment by puja108** [comment]
> Can we maybe setup something in the Slack blog noise channel?

we have full twitter integration in #social

**Comment by xh3b4sd** [comment]
> Post is scheduled in HubSpot for next day early a.m.

I can add more information there. What I still do not understand is how the scheduling works. Like, is the merge event necessary for the pipeline? How does the system know which post to pick from the repo?

**Comment by tommyhobin** [comment]
Cool, thanks. The merge event is not necessary for the scheduling, just the approval. The scheduling is done by hand so your content goes out with out to the right channel (twitter), whenever I schedule it. This post is not attached to an article and so it sits alone without being a part of the repo. 

If we're getting mixed up in our dev and marketing jargon, I'll happily walk you through the Hubspot social scheduler.

**Comment by xh3b4sd** [comment]
Does that mean you take the post, copy it, and put it somewhere? Because we should automate this import then down the road. Not now now, but soon.

**Comment by xh3b4sd** [comment]
Just going with this regardless our discussion.

**Comment by annaloew** [comment]
@xh3b4sd maybe we can have a short hangout about your tweet routine tomorrow or during our next meeting? Don't get me wrong but t I really don't get it. I don't want us as a company to push out sentences like: "When running an organization you want to have #smallteams working on their dedicated story (...)" because is is a) not a rule, but something that only applies in the current status to GS (and is not written in stone) and b) this sounds like we know everything best, which we don't". I don't want to create room for interpretation and controversion here, to be honest.

**Pull request merged**
